/**
 * Template-reference detection for external_api tools (#229).
 *
 * The backend substitutes {{args.X}} and {{env.X}} placeholders inside an
 * external_api tool's request config at dispatch time. This module mirrors
 * that grammar on the frontend so the config form can detect references
 * live, derive an args_schema that matches them, and warn when the two
 * drift apart (the failure mode behind #219).
 *
 * Scope caveat: the form scans raw field text, including the unparsed body
 * draft. Refs inside body JSON keys are counted even though the backend
 * only substitutes values; the worst case is a benign extra schema entry,
 * and all warnings driven by this module are non-blocking.
 */

/**
 * Mirror of the backend template regex.
 * Source of truth: backend/src/taskorbit/tools/generic_api.py (_TEMPLATE_PATTERN).
 * Keep the two in lockstep: whitespace is allowed just inside the braces,
 * keys start with a letter or underscore and may contain dots for nesting.
 * Known engine divergence: Python and JS disagree on a few exotic \s code
 * points (U+0085, U+FEFF); only reachable by pasting control characters,
 * and the warnings driven by this scan are non-blocking either way.
 */
export const TEMPLATE_REF_SOURCE = String.raw`\{\{\s*(env|args)\.([A-Za-z_][A-Za-z0-9_.]*)\s*\}\}`;

export type RefLocation = "url" | "query" | "headers" | "body";

export type DetectedArg = {
  /** Top-level arg name: {{args.user.id}} detects as "user". */
  name: string;
  /** True when any ref under this name used a dotted path (implies object type). */
  nested: boolean;
  /** Where the refs were found, deduped, in detection order. */
  locations: RefLocation[];
};

export type TemplateScan = {
  args: DetectedArg[];
  envRefs: string[];
};

/**
 * Scan field texts for template references. Callers pass VALUES only
 * (URL string, header values, query values, raw body draft text). Header
 * and query keys are never substituted by the backend, so they must not
 * be scanned.
 */
export function scanTemplateRefs(
  sources: Array<{ location: RefLocation; text: string }>,
): TemplateScan {
  const argsByName = new Map<string, DetectedArg>();
  const envRefs: string[] = [];

  for (const { location, text } of sources) {
    // Legacy configs created outside the form may carry non-string header or
    // query values (the backend str()-coerces them at request time); skip
    // them instead of crashing on matchAll.
    if (typeof text !== "string" || !text) continue;
    // A fresh RegExp per scan: a shared "g"-flagged instance would leak
    // lastIndex state between calls.
    const pattern = new RegExp(TEMPLATE_REF_SOURCE, "g");
    for (const match of text.matchAll(pattern)) {
      const namespace = match[1];
      const key = match[2];
      if (namespace === "env") {
        if (!envRefs.includes(key)) envRefs.push(key);
        continue;
      }
      const topSegment = key.split(".")[0];
      const nested = key.includes(".");
      const existing = argsByName.get(topSegment);
      if (existing) {
        existing.nested = existing.nested || nested;
        if (!existing.locations.includes(location)) existing.locations.push(location);
      } else {
        argsByName.set(topSegment, { name: topSegment, nested, locations: [location] });
      }
    }
  }

  return { args: [...argsByName.values()], envRefs };
}

/**
 * Build the args_schema the backend expects for the detected args. Every
 * referenced arg is required: the backend raises a substitution error for
 * any missing ref, so optional args do not exist at this layer. Zero args
 * returns the same shape as the form's empty default (no "required" key).
 */
export function buildArgsSchema(args: DetectedArg[]): Record<string, unknown> {
  if (args.length === 0) return { type: "object", properties: {} };
  const properties: Record<string, unknown> = {};
  for (const arg of args) {
    properties[arg.name] = { type: arg.nested ? "object" : "string" };
  }
  return {
    type: "object",
    required: args.map((a) => a.name),
    properties,
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * True when the schema is something buildArgsSchema could have produced:
 * only {type, properties, required} keys, type "object", every property
 * exactly {type: "string"} or {type: "object"}, and required matching the
 * property names as a set. Any manual addition (enum, description, extra
 * keys, other types) returns false, which permanently pauses auto-fill
 * for that tool. Malformed shapes return false rather than throwing.
 */
export function isAutoGeneratedSchema(schema: Record<string, unknown>): boolean {
  if (!isPlainObject(schema)) return false;
  const allowedKeys = new Set(["type", "properties", "required"]);
  if (Object.keys(schema).some((k) => !allowedKeys.has(k))) return false;
  if (schema.type !== "object") return false;
  if (!isPlainObject(schema.properties)) return false;

  const propertyNames = Object.keys(schema.properties);
  for (const name of propertyNames) {
    const prop = schema.properties[name];
    if (!isPlainObject(prop)) return false;
    const propKeys = Object.keys(prop);
    if (propKeys.length !== 1 || propKeys[0] !== "type") return false;
    if (prop.type !== "string" && prop.type !== "object") return false;
  }

  const required = schema.required ?? [];
  if (!Array.isArray(required)) return false;
  if (required.some((entry) => typeof entry !== "string")) return false;
  const requiredSet = new Set(required as string[]);
  if (requiredSet.size !== propertyNames.length) return false;
  return propertyNames.every((name) => requiredSet.has(name));
}

/**
 * Compare a schema against the detected args by name. Degrades gracefully
 * on malformed schemas (missing or non-object properties, non-array
 * required) by treating those parts as empty.
 */
export function diffSchemaAgainstArgs(
  schema: Record<string, unknown>,
  args: DetectedArg[],
): { missingFromSchema: string[]; unreferencedRequired: string[] } {
  const properties =
    isPlainObject(schema) && isPlainObject(schema.properties) ? Object.keys(schema.properties) : [];
  const required =
    isPlainObject(schema) && Array.isArray(schema.required)
      ? (schema.required.filter((entry) => typeof entry === "string") as string[])
      : [];

  const detectedNames = args.map((a) => a.name);
  const missingFromSchema = detectedNames.filter((name) => !properties.includes(name));
  const unreferencedRequired = required.filter((name) => !detectedNames.includes(name));
  return { missingFromSchema, unreferencedRequired };
}

/**
 * Add detected args the schema does not know about yet. Strictly additive:
 * existing properties are preserved verbatim (manual enums, descriptions,
 * types all survive), required entries are unioned, and unreferenced
 * entries are never removed.
 */
export function addMissingArgsToSchema(
  schema: Record<string, unknown>,
  args: DetectedArg[],
): Record<string, unknown> {
  const base = isPlainObject(schema) ? schema : {};
  const properties: Record<string, unknown> = isPlainObject(base.properties)
    ? { ...base.properties }
    : {};
  const required: string[] = Array.isArray(base.required)
    ? [...(base.required.filter((entry) => typeof entry === "string") as string[])]
    : [];

  for (const arg of args) {
    if (!(arg.name in properties)) {
      properties[arg.name] = { type: arg.nested ? "object" : "string" };
    }
    if (!required.includes(arg.name)) required.push(arg.name);
  }

  return { ...base, type: base.type ?? "object", required, properties };
}

/** Key-order-insensitive deep equality for schema objects. */
export function argsSchemasEqual(a: unknown, b: unknown): boolean {
  if (Object.is(a, b)) return true;
  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((item, i) => argsSchemasEqual(item, b[i]));
  }
  if (isPlainObject(a) && isPlainObject(b)) {
    const keysA = Object.keys(a);
    const keysB = Object.keys(b);
    if (keysA.length !== keysB.length) return false;
    return keysA.every((key) => key in b && argsSchemasEqual(a[key], b[key]));
  }
  return false;
}
