/**
 * Tests for externalApiArgs (#229).
 *
 * The scan grammar must exactly mirror the backend _TEMPLATE_PATTERN in
 * backend/src/taskorbit/tools/generic_api.py. If a case here changes, check
 * the backend regex first.
 */

import { describe, expect, it } from "vitest";

import {
  addMissingArgsToSchema,
  argsSchemasEqual,
  buildArgsSchema,
  diffSchemaAgainstArgs,
  isAutoGeneratedSchema,
  scanTemplateRefs,
  type DetectedArg,
} from "./externalApiArgs";

const url = (text: string) => [{ location: "url" as const, text }];

describe("scanTemplateRefs grammar", () => {
  it("detects a plain args ref in the URL", () => {
    const scan = scanTemplateRefs(url("https://x/{{args.city}}"));
    expect(scan.args).toEqual([{ name: "city", nested: false, locations: ["url"] }]);
    expect(scan.envRefs).toEqual([]);
  });

  it("accepts whitespace just inside the braces", () => {
    const scan = scanTemplateRefs(url("https://x/{{ args.city }}"));
    expect(scan.args.map((a) => a.name)).toEqual(["city"]);
  });

  it("rejects whitespace around the dot separator", () => {
    expect(scanTemplateRefs(url("{{args .city}}")).args).toEqual([]);
    expect(scanTemplateRefs(url("{{args. city}}")).args).toEqual([]);
  });

  it("rejects keys starting with a digit", () => {
    expect(scanTemplateRefs(url("{{args.2fast}}")).args).toEqual([]);
  });

  it("accepts keys starting with an underscore", () => {
    expect(scanTemplateRefs(url("{{args._private}}")).args.map((a) => a.name)).toEqual([
      "_private",
    ]);
  });

  it("collapses dotted refs to the top segment and marks them nested", () => {
    const scan = scanTemplateRefs(url("{{args.user.id}}"));
    expect(scan.args).toEqual([{ name: "user", nested: true, locations: ["url"] }]);
  });

  it("merges plain and dotted refs of the same top name into one nested arg", () => {
    const scan = scanTemplateRefs([
      { location: "url", text: "{{args.user}}" },
      { location: "body", text: '{"id": "{{args.user.id}}"}' },
    ]);
    expect(scan.args).toEqual([{ name: "user", nested: true, locations: ["url", "body"] }]);
  });

  it("separates env refs from args and dedupes them", () => {
    const scan = scanTemplateRefs([
      { location: "headers", text: "Bearer {{env.API_KEY}}" },
      { location: "query", text: "{{env.API_KEY}}" },
    ]);
    expect(scan.args).toEqual([]);
    expect(scan.envRefs).toEqual(["API_KEY"]);
  });

  it("finds multiple refs plus literal text in a single string", () => {
    const scan = scanTemplateRefs(url("https://x/{{args.a}}/{{args.b}}?k={{env.K}}"));
    expect(scan.args.map((a) => a.name)).toEqual(["a", "b"]);
    expect(scan.envRefs).toEqual(["K"]);
  });

  it("ignores unknown namespaces", () => {
    const scan = scanTemplateRefs(url("{{other.name}} {{argsx.name}}"));
    expect(scan.args).toEqual([]);
    expect(scan.envRefs).toEqual([]);
  });

  it("dedupes the same arg across locations and merges locations in order", () => {
    const scan = scanTemplateRefs([
      { location: "url", text: "{{args.city}}" },
      { location: "query", text: "{{args.city}}" },
    ]);
    expect(scan.args).toEqual([{ name: "city", nested: false, locations: ["url", "query"] }]);
  });

  it("scans raw body text including nested strings and array items", () => {
    const body = '{"a": {"b": "{{args.deep}}"}, "list": ["{{args.item}}", 5]}';
    const scan = scanTemplateRefs([{ location: "body", text: body }]);
    expect(scan.args.map((a) => a.name)).toEqual(["deep", "item"]);
  });

  it("does not crash on body text with non-string scalars", () => {
    const scan = scanTemplateRefs([{ location: "body", text: '{"n": 5, "b": true, "x": null}' }]);
    expect(scan.args).toEqual([]);
  });

  it("returns empty results for empty input", () => {
    expect(scanTemplateRefs([])).toEqual({ args: [], envRefs: [] });
    expect(scanTemplateRefs(url(""))).toEqual({ args: [], envRefs: [] });
  });

  it("skips non-string values from legacy configs instead of crashing", () => {
    const sources = [
      { location: "headers" as const, text: 3 as unknown as string },
      { location: "query" as const, text: null as unknown as string },
      { location: "url" as const, text: "{{args.city}}" },
    ];
    expect(scanTemplateRefs(sources).args.map((a) => a.name)).toEqual(["city"]);
  });

  it("rejects malformed refs", () => {
    expect(scanTemplateRefs(url("{{args.}}")).args).toEqual([]);
    expect(scanTemplateRefs(url("{{args}}")).args).toEqual([]);
    expect(scanTemplateRefs(url("{{args.city")).args).toEqual([]);
  });

  it("returns identical results on back-to-back scans of the same input", () => {
    const sources = url("{{args.a}} {{args.b}}");
    expect(scanTemplateRefs(sources)).toEqual(scanTemplateRefs(sources));
  });
});

describe("buildArgsSchema", () => {
  it("returns the form's empty default shape with no required key for zero args", () => {
    const schema = buildArgsSchema([]);
    expect(schema).toEqual({ type: "object", properties: {} });
    expect("required" in schema).toBe(false);
  });

  it("marks every detected arg required, nested args as objects", () => {
    const args: DetectedArg[] = [
      { name: "city", nested: false, locations: ["url"] },
      { name: "user", nested: true, locations: ["body"] },
    ];
    expect(buildArgsSchema(args)).toEqual({
      type: "object",
      required: ["city", "user"],
      properties: { city: { type: "string" }, user: { type: "object" } },
    });
  });
});

describe("isAutoGeneratedSchema", () => {
  it("accepts the empty default and builder outputs", () => {
    expect(isAutoGeneratedSchema({ type: "object", properties: {} })).toBe(true);
    expect(
      isAutoGeneratedSchema(buildArgsSchema([{ name: "city", nested: false, locations: ["url"] }])),
    ).toBe(true);
  });

  it("rejects any manual customization", () => {
    expect(
      isAutoGeneratedSchema({
        type: "object",
        required: ["city"],
        properties: { city: { type: "string", enum: ["Berlin"] } },
      }),
    ).toBe(false);
    expect(
      isAutoGeneratedSchema({
        type: "object",
        required: ["city"],
        properties: { city: { type: "string", description: "a city" } },
      }),
    ).toBe(false);
    expect(
      isAutoGeneratedSchema({
        type: "object",
        required: ["city"],
        properties: { city: { type: "string" } },
        additionalProperties: false,
      }),
    ).toBe(false);
    expect(
      isAutoGeneratedSchema({
        type: "object",
        required: ["n"],
        properties: { n: { type: "integer" } },
      }),
    ).toBe(false);
    expect(
      isAutoGeneratedSchema({
        type: "object",
        required: [],
        properties: { city: { type: "string" } },
      }),
    ).toBe(false);
    expect(isAutoGeneratedSchema({ type: "array", properties: {} })).toBe(false);
  });

  it("returns false for malformed shapes without throwing", () => {
    expect(isAutoGeneratedSchema({ type: "object", properties: {}, required: "city" })).toBe(false);
    expect(isAutoGeneratedSchema({ type: "object", properties: [] as unknown as object })).toBe(
      false,
    );
    expect(isAutoGeneratedSchema(null as unknown as Record<string, unknown>)).toBe(false);
  });
});

describe("diffSchemaAgainstArgs", () => {
  const detected: DetectedArg[] = [
    { name: "city", nested: false, locations: ["url"] },
    { name: "date", nested: false, locations: ["query"] },
  ];

  it("reports args missing from the schema and unreferenced required entries", () => {
    const schema = {
      type: "object",
      required: ["city", "stale"],
      properties: { city: { type: "string" }, stale: { type: "string" } },
    };
    expect(diffSchemaAgainstArgs(schema, detected)).toEqual({
      missingFromSchema: ["date"],
      unreferencedRequired: ["stale"],
    });
  });

  it("degrades gracefully on malformed schemas", () => {
    expect(diffSchemaAgainstArgs({ required: "nope" }, detected)).toEqual({
      missingFromSchema: ["city", "date"],
      unreferencedRequired: [],
    });
  });
});

describe("addMissingArgsToSchema", () => {
  it("adds missing args while preserving manual edits verbatim", () => {
    const manual = {
      type: "object",
      required: ["city", "stale"],
      properties: {
        city: { type: "string", enum: ["Berlin", "Munich"] },
        stale: { type: "string" },
      },
    };
    const detected: DetectedArg[] = [
      { name: "city", nested: false, locations: ["url"] },
      { name: "date", nested: false, locations: ["query"] },
    ];
    expect(addMissingArgsToSchema(manual, detected)).toEqual({
      type: "object",
      required: ["city", "stale", "date"],
      properties: {
        city: { type: "string", enum: ["Berlin", "Munich"] },
        stale: { type: "string" },
        date: { type: "string" },
      },
    });
  });

  it("does not duplicate required entries", () => {
    const schema = { type: "object", required: ["city"], properties: { city: { type: "string" } } };
    const detected: DetectedArg[] = [{ name: "city", nested: false, locations: ["url"] }];
    expect(addMissingArgsToSchema(schema, detected)).toEqual(schema);
  });
});

describe("argsSchemasEqual", () => {
  it("compares deeply, ignoring key order", () => {
    expect(
      argsSchemasEqual(
        { type: "object", required: ["a"], properties: { a: { type: "string" } } },
        { properties: { a: { type: "string" } }, required: ["a"], type: "object" },
      ),
    ).toBe(true);
    expect(argsSchemasEqual({ required: ["a"] }, { required: ["b"] })).toBe(false);
    expect(argsSchemasEqual({ required: ["a"] }, { required: ["a", "b"] })).toBe(false);
  });
});
